version: '3'

services:
  docker-socket-tcp:
    container_name: docker-socket-tcp
    image: ghcr.io/aaronbolton/docker-socket-tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2375:2375"
